/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_project_onepice_basicproject_ndkExample_JniUtils */

#ifndef _Included_com_project_onepice_basicproject_ndkExample_JniUtils
#define _Included_com_project_onepice_basicproject_ndkExample_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_project_onepice_basicproject_ndkExample_JniUtils
 * Method:    getStringFormC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_project_onepice_basicproject_ndkExample_JniUtils_getStringFormC
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
